### ISSUE TITLE
Voting Feature Concept ⬆️  (Please Read!)

### ISSUE THREAD

**Issue by CreeperPlanet26** [CreeperPlanet26/Cool-Bot-List#36]
# Information

This is what a voting system would look like. Comment bellow if you understand this and everything makes sence or if you have any questions.

| Branch     | Feature | Description
| ----------- | ----------- |----------|
| vote-feature   | GET api/users/vote | Should return the users.vote object. from the db.
| vote-feature   | POST api/users/vote/:botId/:userId | Takes the userId, botId from the parms and changes the user.vote object to have the botId property. Should update the bot to have 1 more vote. This method should not let the user.vote object be changed if the date on the object is less that 12 hours than the current date. |
| vote-feature  | Mongoose Model | This should have a property on the user object called vote. This should have botId and date properties. botId should be required. date should not be required and set to th current date by default. |
| vote-feature  | Captcha  | Not sure if this is a backend thing. Correct me in the comments if I'm wrong. We should have a captcha if they awnser correctly, their vote will be submitted.  |
| vote-feature  | Other Features | Comment down bellow any features you have thought of. Be sure to comment if I missed anything as well |
| vote-feature  | Confusingness | If your confused comment with your question and I will try to reword whatever th best I can.  |
| vote-feature | 1 month reset | Resets the bot.vote every 1 month|

**Comment by Maxisthemoose** [comment]
huh

**Comment by CreeperPlanet26** [comment]
I'll explain soon

**Comment by CreeperPlanet26** [comment]
Ight I finished typing this.

**Comment by Maxisthemoose** [comment]
12h seems fine

**Comment by Maxisthemoose** [comment]
And shouldn't the bot schema have a property for vote totals?

**Comment by CreeperPlanet26** [comment]
> 12h seems fine

Ight I'll edit it with that then.

**Comment by CreeperPlanet26** [comment]
> And shouldn't the bot schema have a property for vote totals?
> 

Adding this and the 1 month reset thing rn.

**Comment by Maxisthemoose** [comment]
What branch should I create the voting branch off of

**Comment by CreeperPlanet26** [comment]
The notis branch. But do all the notis work we should test all of those first then merge it into master
