### ISSUE TITLE
Bots should have Tags

### ISSUE THREAD

**Issue by Maxisthemoose** [CreeperPlanet26/Cool-Bot-List#37]
I am mostly just opening this issue for ideas for the schemas, but the fist one that comes to mind is Bot Tags, we can use this thread to keep track of new ideas to add to the schema. Rn, `Bot Tags`

**Comment by CreeperPlanet26** [comment]
That's actually a good idea. We can use that to implement a search feature as well.

**Comment by Maxisthemoose** [comment]
Alright yeah, we would be able to sort bots by tags then too, so it'll just make navigation on the website nicer to9

**Comment by CreeperPlanet26** [comment]
Yeah on the main bots page we would have pagination and u can filter and search  for bots by tag, votes and/or reviews. This would be done using array manipulation. (filters, other)

**Comment by Maxisthemoose** [comment]
Yeah, sounds good
